# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191103_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='访问地址'),
        ),
    ]
